version: '3'

services:
  postgres:
    container_name: postgres_clinic
    image: postgres:15.3
    restart: always
    environment:
       POSTGRES_DB: clinic
       POSTGRES_USER: otajonov
       POSTGRES_PASSWORD: quvonchbek
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - clinic_network
    ports:
      - "5434:5432"  # Map container's port 5432 to host's port 5434

  clinic:
    build: .
    ports:
      - "8081:8081"
    environment:
       POSTGRES_HOST: postgres
       POSTGRES_PORT: 5432
       POSTGRES_USER: otajonov
       POSTGRES_PASSWORD: quvonchbek
       POSTGRES_DB: clinic

       HTTP_PORT: 8081
       SIGN_KEY: clinic
       LOG_LEVEL: debug
       ENVIRONMENT: developer
    volumes:
      - media:/app/media
    networks:
      - clinic_network
    depends_on:
      - postgres
    restart: always

networks:
  clinic_network:  # Create a custom Docker network
    driver: bridge  # You can change the driver as needed

volumes:
  media:
  postgres-data:
